name: "Quokka Analysis"
description: "Submit app file to the Quokka (Kryptowire) Portal for analysis"
inputs:
  path-to-file:
    description: "Path to the artifact file"
    required: true
  platform:
    description: "Platform the app belongs to"
    required: true
  apiKey:
    description: "API Key for the user"
    required: true
  fast-scan:
    description: "Enable fast scan (lite scan) mode"
    required: false
    default: "false"
runs:
  using: 'node20'
  main: 'dist/index.js' 
branding:
  icon: "award"
  color: "green"

